"""E2E-Szenario für den KI-Theme-Autor."""

import json
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

PROVIDER_ID = "e2e-theme-provider"
MODEL_ID = "mock-theme"


class _MockHandler(BaseHTTPRequestHandler):
    received_user = None
    received_stream = None

    def do_POST(self):
        if self.path != "/v1/chat/completions":
            self.send_error(404)
            return
        length = int(self.headers.get("Content-Length", "0"))
        payload = json.loads(self.rfile.read(length).decode("utf-8"))
        type(self).received_stream = payload.get("stream")
        user = next(
            (
                message.get("content", "")
                for message in payload.get("messages", [])
                if message.get("role") == "user"
            ),
            "",
        )
        type(self).received_user = user

        theme_json = json.dumps({
            "manifest": {
                "name": "E2E AI Theme",
                "description": "Generated by E2E",
                "code": "light",
                "cover": True,
                "header": False,
                "footer": False,
                "hideInlineFrontmatter": False,
                "formatVersion": 1
            },
            "contentCss": ".markdown-body { color: green; }"
        }, ensure_ascii=False)

        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()

        chunk_size = 20
        for i in range(0, len(theme_json), chunk_size):
            delta = theme_json[i:i + chunk_size]
            event = (
                "data: "
                + json.dumps(
                    {"choices": [{"delta": {"content": delta}}]},
                    ensure_ascii=False,
                )
                + "\r\n\r\n"
            ).encode("utf-8")
            self.wfile.write(event)
            self.wfile.flush()
            time.sleep(0.01)

        self.wfile.write(b"data: [DONE]\r\n\r\n")
        self.wfile.flush()

    def log_message(self, _format, *_args):
        return


def _poll(predicate, timeout_s: float = 10.0):
    deadline = time.monotonic() + timeout_s
    value = None
    while time.monotonic() < deadline:
        value = predicate()
        if value:
            return value
        time.sleep(0.05)
    return value


def _eval(ctx, js: str):
    response = ctx.api.eval(js, timeout_ms=10_000)
    ctx.expect(response.get("ok") is True, f"/eval schlug fehl: {response!r}")
    return response.get("value")


def _configure_provider(ctx, base_url: str):
    script = f"""(async () => {{
        await window.__folioInvoke("ai_custom_upsert", {{
            definition: {{
                id: {PROVIDER_ID!r},
                name: "E2E Theme Mock",
                baseURL: {base_url!r}
            }}
        }});
        await window.__folioInvoke("ai_model_toggle", {{
            providerId: {PROVIDER_ID!r},
            modelId: {MODEL_ID!r},
            on: true
        }});
        await window.__folioInvoke("ai_default_model_set", {{
            providerId: {PROVIDER_ID!r},
            modelId: {MODEL_ID!r}
        }});
        return true;
    }})()"""
    return _eval(ctx, script)


def _cleanup_provider(ctx):
    try:
        _eval(
            ctx,
            f"""Promise.allSettled([
                window.__folioInvoke("ai_auth_remove", {{
                    providerId: {PROVIDER_ID!r}
                }}),
                window.__folioInvoke("ai_custom_delete", {{
                    id: {PROVIDER_ID!r}
                }})
            ])""",
        )
    except Exception:
        pass


def run(ctx):
    _MockHandler.received_user = None
    _MockHandler.received_stream = None
    server = ThreadingHTTPServer(("127.0.0.1", 0), _MockHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()

    try:
        _cleanup_provider(ctx)

        with ctx.step("lokalen Mock-Provider konfigurieren"):
            base_url = f"http://127.0.0.1:{server.server_port}/v1"
            ctx.expect(_configure_provider(ctx, base_url) is True, "Provider-Setup failed")

        with ctx.step("Theme-Editor öffnen"):
            _eval(ctx, "window.openThemeEditor('brand')")
            visible = _poll(
                lambda: (
                    (snapshot := ctx.api.dom("#theme-editor-dialog")).get("exists")
                    and "hidden" not in (snapshot.get("attributes") or {})
                )
            )
            ctx.expect(bool(visible), "Theme-Editor wurde nicht sichtbar")

        with ctx.step("Mit KI anpassen Dialog öffnen"):
            ctx.api.click("theme-editor-ai")
            ai_dialog_visible = _poll(
                lambda: (
                    (snapshot := ctx.api.dom("#theme-ai-dialog")).get("exists")
                    and "hidden" not in (snapshot.get("attributes") or {})
                )
            )
            ctx.expect(bool(ai_dialog_visible), "Theme KI Dialog wurde nicht sichtbar")

        with ctx.step("Prompt eingeben und KI-Lauf starten"):
            _eval(
                ctx,
                """(() => {
                    document.getElementById("theme-ai-prompt").value = "Ein neongrünes Theme für Programmierer";
                })()""",
            )
            ctx.api.click("theme-ai-start")

            # Warte, bis die Generierung fertig ist und der Dialog schließt
            closed = _poll(
                lambda: (
                    (snapshot := ctx.api.dom("#theme-ai-dialog")).get("exists")
                    and "hidden" in (snapshot.get("attributes") or {})
                ),
                timeout_s=15.0,
            )
            ctx.expect(bool(closed), "Theme KI Dialog wurde nach Generation nicht geschlossen")

        with ctx.step("Prüfen, dass die Buffer den Draft enthalten und NICHT gespeichert wurde"):
            content_css = _eval(ctx, "window.FolioThemeEditor.getPart('content')")
            is_dirty = _eval(ctx, "window.FolioThemeEditor.isDirty()")

            ctx.expect("green" in (content_css or ""), f"Vorgeschlagenes CSS fehlt in den Buffern: {content_css}")
            ctx.expect(is_dirty is True, "Buffer wurde fälschlicherweise automatisch gespeichert")

    finally:
        _cleanup_provider(ctx)
        try:
            ctx.api.click("theme-editor-close")
            ctx.api.click("unsaved-discard")
        except Exception:
            pass
        server.shutdown()
        server.server_close()
        thread.join(timeout=2.0)
        # hard absence check OUTSIDE the best-effort try/except (clicks may be no-op if
        # editor not open or early failure); use ctx.expect so leak is detected as test failure.
        # If never opened, length===0 is trivially true. Runs AFTER server teardown so a
        # failing expect cannot leak the mock server thread into later scenarios.
        ctx.expect(
            _poll(
                lambda: _eval(
                    ctx,
                    "document.querySelectorAll('#tab-bar .tab-item[data-tab-id=\"theme-editor\"]').length === 0"
                ),
                timeout_s=2.0,
            ),
            "theme-editor virtual tab still present in #tab-bar",
        )
